// Copyright (c) 2026 Team 801 Horsepower
// ─────────────────────────────────────────────────────────────────────────────
//  GENERATED FILE – base generated by CTRE Tuner X Swerve Project Generator
//  then customised for Team 801 Horsepower's CTRE X2 swerve drivetrain.
//
//  HOW TO UPDATE:
//   1. Open Tuner X → Swerve Generator → enter your hardware CAN IDs and
//      measured steer offsets → Export.
//   2. Copy the generated TunerConstants.java here, replacing this file, OR
//      manually update the TODO blocks below.
// ─────────────────────────────────────────────────────────────────────────────
package frc.robot.generated;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.*;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.*;
import frc.robot.subsystems.DrivetrainSubsystem;

/**
 * All constant values for the CTRE Phoenix 6 swerve drivetrain.
 *
 * <p>These values came from the Tuner X swerve generator. Values marked <b>TODO</b> must be set to
 * match your physical hardware before the robot will drive correctly.
 *
 * <p>Assumes a standard CTRE "Swerve X2" chassis with:
 * <ul>
 *   <li>4 × Kraken X60 drive motors (TalonFX)
 *   <li>4 × Kraken X60 steer motors (TalonFX)
 *   <li>4 × CANcoder absolute encoders
 *   <li>Pigeon 2.0 IMU (used for fast odometry, but heading is overridden by QuestNav)
 *   <li>All on the "rio" CANbus
 * </ul>
 */
public class TunerConstants {

  // ─── CAN Bus ───────────────────────────────────────────────────────────────

  /**
   * The name of the CAN bus your drivetrain is on. If everything is on the roboRIO's built-in bus
   * use "rio". If you have a CANivore rename it here (e.g. "Canivore").
   */
  public static final CANBus kCANBus = new CANBus("rio");

  // ─── Pigeon 2 ──────────────────────────────────────────────────────────────

  /**
   * CAN ID of the Pigeon 2.0 IMU on your drivetrain.
   * TODO: Set to your actual Pigeon 2 CAN ID.
   *
   * <p>Note: The Pigeon is still used by CTRE's high-frequency odometry loop for smooth wheel
   * odometry integration. QuestNav overrides the heading at the pose-estimator level by feeding
   * vision measurements with very tight standard deviations.
   */
  public static final int kPigeonId = 1; // TODO: Set your Pigeon 2 CAN ID

  // ─── Motor / Encoder CAN IDs ───────────────────────────────────────────────
  // TODO: Replace all IDs below with your actual wired CAN IDs from Phoenix Tuner X.

  public static final int kFrontLeftDriveMotorId  = 1;
  public static final int kFrontLeftSteerMotorId  = 2;
  public static final int kFrontLeftEncoderId     = 1;

  public static final int kFrontRightDriveMotorId = 3;
  public static final int kFrontRightSteerMotorId = 4;
  public static final int kFrontRightEncoderId    = 2;

  public static final int kBackLeftDriveMotorId   = 5;
  public static final int kBackLeftSteerMotorId   = 6;
  public static final int kBackLeftEncoderId      = 3;

  public static final int kBackRightDriveMotorId  = 7;
  public static final int kBackRightSteerMotorId  = 8;
  public static final int kBackRightEncoderId     = 4;

  // ─── Steer Encoder Offsets ─────────────────────────────────────────────────
  // These are the CANcoder "Absolute Position" when the wheel is physically pointing forward.
  // Find them in Phoenix Tuner X → CANcoder → Absolute Position (no offset).
  // Negate the displayed value (e.g. 0.1234 becomes -0.1234).
  // TODO: Measure and set your actual offsets!

  private static final double kFrontLeftEncoderOffset  = -0.0; // TODO
  private static final double kFrontRightEncoderOffset = -0.0; // TODO
  private static final double kBackLeftEncoderOffset   = -0.0; // TODO
  private static final double kBackRightEncoderOffset  = -0.0; // TODO

  // ─── Drive Motor Inversion ─────────────────────────────────────────────────
  // Flip to true if that wheel drives in the wrong direction.
  // TODO: Confirm by driving each module individually.

  // true = Clockwise_Positive (inverted), false = CounterClockwise_Positive (default)
  private static final boolean kFrontLeftDriveInverted  = false;
  private static final boolean kFrontRightDriveInverted = true;
  private static final boolean kBackLeftDriveInverted   = false;
  private static final boolean kBackRightDriveInverted  = true;

  // ─── Steer Motor Inversion ─────────────────────────────────────────────────
  // On most CTRE X2 builds the steer is inverted. Verify with Tuner X generator output.
  private static final boolean kSteerMotorInverted = true;

  // ─── Module Geometry (module position relative to robot centre) ────────────
  // Measure centre-to-centre of front and side wheel pair.
  // TODO: Update to match your actual wheelbase/trackwidth (meters).

  /** Half the wheelbase (front-back distance between wheel centres), meters. */
  private static final double kWheelBaseMeters   = 0.5588; // 22 inches default

  /** Half the trackwidth (left-right distance between wheel centres), meters. */
  private static final double kTrackWidthMeters  = 0.5588; // 22 inches default

  // ─── Wheel / Gear Ratio ────────────────────────────────────────────────────

  /** Wheel radius, meters. 2-inch radius = 4-inch (nominal) wheel. */
  public static final double kWheelRadiusMeters = 0.0508; // 2 inches

  /**
   * Drive gear ratio: the number of motor rotations per one wheel rotation.
   * CTRE Swerve X2 typically uses L2 gearing = 6.75:1. Verify against your BOM.
   */
  private static final double kDriveGearRatio = 6.75;

  /**
   * Steer (azimuth) gear ratio: motor rotations per full module rotation.
   * MK4i steer = 150/7 ≈ 21.43:1. Verify against your BOM.
   */
  private static final double kSteerGearRatio = 150.0 / 7.0;

  // ─── Drive Motor PID / Feed-Forward ────────────────────────────────────────
  // Use SysId or empirical tuning to refine these values.

  private static final Slot0Configs kDriveGains = new Slot0Configs()
      .withKP(0.1).withKI(0).withKD(0)
      .withKS(0.1).withKV(0.12).withKA(0.01);

  // ─── Steer Motor PID ───────────────────────────────────────────────────────

  private static final Slot0Configs kSteerGains = new Slot0Configs()
      .withKP(100).withKI(0).withKD(0.5)
      .withKS(0.1).withKV(1.59).withKA(0);

  // ─── Closed-Loop Output Type ───────────────────────────────────────────────

  private static final ClosedLoopOutputType kDriveClosedLoopOutput = ClosedLoopOutputType.Voltage;
  private static final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.Voltage;

  // ─── Motor Type ────────────────────────────────────────────────────────────

  private static final DriveMotorArrangement kDriveMotorType = DriveMotorArrangement.TalonFX_Integrated;
  private static final SteerMotorArrangement kSteerMotorType = SteerMotorArrangement.TalonFX_Integrated;

  // ─── Current Limits ────────────────────────────────────────────────────────

  private static final Current kSlipCurrentAmps = Amps.of(120.0);
  private static final Current kDriveCurrentLimitAmps = Amps.of(120.0);
  private static final Current kSteerCurrentLimitAmps = Amps.of(40.0);

  // ─── Odometry Standard Deviations ─────────────────────────────────────────

  /**
   * Wheel odometry standard deviations [X m, Y m, θ rad]. These represent how much we trust the
   * wheel/Pigeon odometry between QuestNav updates.
   */
  public static final Matrix<N3, N1> kOdometryStdDevs = VecBuilder.fill(0.1, 0.1, 0.1);

  /**
   * Vision (QuestNav) standard deviations [X m, Y m, θ rad]. Very low values make QuestNav the
   * dominant source of heading and position data.
   *
   * <p>These are duplicated in Constants.QuestNavConstants for clarity; if you change one, change
   * the other.
   */
  public static final Matrix<N3, N1> kVisionStdDevs = VecBuilder.fill(0.02, 0.02, 0.035);

  // ─── Module Constants Factory ──────────────────────────────────────────────

  private static final SwerveModuleConstantsFactory<
      TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> ConstantCreator =
      new SwerveModuleConstantsFactory<
          TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
          .withDriveMotorGearRatio(kDriveGearRatio)
          .withSteerMotorGearRatio(kSteerGearRatio)
          .withCouplingGearRatio(3.5)           // X2 coupling ratio – verify for your modules
          .withWheelRadius(Meters.of(kWheelRadiusMeters))
          .withDriveMotorGains(kDriveGains)
          .withSteerMotorGains(kSteerGains)
          .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
          .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
          .withSlipCurrent(kSlipCurrentAmps)
          .withDriveMotorInitialConfigs(new TalonFXConfiguration()
              .withCurrentLimits(new CurrentLimitsConfigs()
                  .withStatorCurrentLimit(kDriveCurrentLimitAmps)
                  .withStatorCurrentLimitEnable(true)))
          .withSteerMotorInitialConfigs(new TalonFXConfiguration()
              .withCurrentLimits(new CurrentLimitsConfigs()
                  .withStatorCurrentLimit(kSteerCurrentLimitAmps)
                  .withStatorCurrentLimitEnable(true)))
          .withFeedbackSource(SteerFeedbackType.FusedCANcoder)
          .withDriveMotorType(kDriveMotorType)
          .withSteerMotorType(kSteerMotorType);

  // ─── Per-Module Constants ──────────────────────────────────────────────────

  public static final SwerveModuleConstants<
      TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontLeft =
      ConstantCreator.createModuleConstants(
          kFrontLeftSteerMotorId,
          kFrontLeftDriveMotorId,
          kFrontLeftEncoderId,
          kFrontLeftEncoderOffset,
          Meters.of( kTrackWidthMeters),   // +X = front
          Meters.of( kWheelBaseMeters),    // +Y = left
          kFrontLeftDriveInverted,
          kSteerMotorInverted);

  public static final SwerveModuleConstants<
      TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontRight =
      ConstantCreator.createModuleConstants(
          kFrontRightSteerMotorId,
          kFrontRightDriveMotorId,
          kFrontRightEncoderId,
          kFrontRightEncoderOffset,
          Meters.of( kTrackWidthMeters),   // +X = front
          Meters.of(-kWheelBaseMeters),    // -Y = right
          kFrontRightDriveInverted,
          kSteerMotorInverted);

  public static final SwerveModuleConstants<
      TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackLeft =
      ConstantCreator.createModuleConstants(
          kBackLeftSteerMotorId,
          kBackLeftDriveMotorId,
          kBackLeftEncoderId,
          kBackLeftEncoderOffset,
          Meters.of(-kTrackWidthMeters),   // -X = back
          Meters.of( kWheelBaseMeters),    // +Y = left
          kBackLeftDriveInverted,
          kSteerMotorInverted);

  public static final SwerveModuleConstants<
      TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackRight =
      ConstantCreator.createModuleConstants(
          kBackRightSteerMotorId,
          kBackRightDriveMotorId,
          kBackRightEncoderId,
          kBackRightEncoderOffset,
          Meters.of(-kTrackWidthMeters),   // -X = back
          Meters.of(-kWheelBaseMeters),    // -Y = right
          kBackRightDriveInverted,
          kSteerMotorInverted);

  // ─── Drivetrain Constants ──────────────────────────────────────────────────

  public static final SwerveDrivetrainConstants DrivetrainConstants =
      new SwerveDrivetrainConstants()
          .withCANBusName(kCANBus.getName())
          .withPigeon2Id(kPigeonId)
          .withPigeon2Configs(null); // Use default Pigeon 2 config

  // ─── CommandSwerveDrivetrain ────────────────────────────────────────────────

  /**
   * Factory method that creates the {@link DrivetrainSubsystem} with all four modules and the
   * QuestNav-aware vision standard deviations.
   *
   * <p>Call this once in {@code RobotContainer} and store the result.
   */
  public static DrivetrainSubsystem createDrivetrain() {
    return new DrivetrainSubsystem(
        DrivetrainConstants,
        250.0, // Odometry thread frequency (Hz) – 250 Hz on CAN FD
        kOdometryStdDevs,
        kVisionStdDevs,
        FrontLeft,
        FrontRight,
        BackLeft,
        BackRight);
  }
}